parameters:
  vmImage: 'macOS-10.14'
  name: macOS_10_14
  excludeXcode: $(excludeXcode)
jobs:
  - job: ${{ parameters.name }}
    variables:
      EXCLUDE_XCODE: ${{ parameters.excludeXcode }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
    - script: ls /Applications/
      displayName: List Installed Applications
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x' 
    - script: npm install
      displayName: Install Node Modules
    - script: mkdir -p Resources/WebDriverAgent.bundle
      displayName: Make Resources Folder
    - script: node ./ci-jobs/scripts/build-webdriveragents.js
      displayName: Build WebDriverAgents
    - script: ls ./bundles
      displayName: List WDA Bundles
    - task: PublishPipelineArtifact@0
      inputs:
        targetPath: bundles/
        artifactName: ${{ parameters.name }}
    - task: GithubRelease@0
      displayName: Publish to GitHub Release
      inputs:
        githubConnection: appiumbot
        repositoryName: appium/WebDriverAgent
        tag: $(Build.BuildNumber)
        assets: bundles/