name: 'Setup Xcode Test Environment'
description: 'Common setup steps for Xcode tests'

inputs:
  node_version:
    description: 'Node.js version to use'
    required: true
  xcode_version:
    description: 'Xcode version to use'
    required: true
  ruby_version:
    description: 'Ruby version to use'
    required: false
    default: '3.3'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node_version }}
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ inputs.xcode_version }}
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby_version }}
    - name: Install dependencies
      run: |
        bundle install
        mkdir -p ./Resources/WebDriverAgent.bundle
      shell: bash

