//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface NSValue (XCTestAdditions)
+ (id)xct_valueWithCGRect:(struct CGRect)arg1;
@property(readonly) struct CGRect xct_CGRectValue;
- (id)xct_contentDescription;
@end

