//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface XCSourceCodeTreeNodeEnumerator : NSObject
{
    NSMutableArray *_remainingNodes;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *remainingNodes; // @synthesize remainingNodes=_remainingNodes;
- (id)nextObject;
- (id)initWithNode:(id)arg1;

@end

