//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCSynthesizedEventRecord_h
#define XCSynthesizedEventRecord_h
@import Foundation;
@import UIKit;

@class NSArray, NSDictionary, NSMutableArray, NSObject, NSString;

@interface XCSynthesizedEventRecord : NSObject <NSSecureCoding>

@property (readonly) NSArray *eventPaths;
@property (readonly, copy) NSString *name;
@property (readonly) double maximumOffset;
@property (readonly) long long interfaceOrientation;
@property long long targetProcessID;
@property (readonly) unsigned long long displayID;
@property _Bool beginsPersistentState;
@property _Bool endsPersistentState;
@property (nonatomic) CGVector originalOffset;
@property (copy) NSDictionary *systemAutomationProperties;
@property CGSize parentWindowSize;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (id)utIdentifierString;

/* instance methods */
- (_Bool)synthesizeWithError:(id *)error;
- (id)initWithName:(id)name displayID:(unsigned long long)id interfaceOrientation:(long long)orientation;
- (void)unsetInterfaceOrientation;
- (id)initWithName:(id)name;
- (id)initWithName:(id)name displayID:(unsigned long long)id;
- (id)initWithName:(id)name interfaceOrientation:(long long)orientation;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (void)addPointerEventPath:(id)path;
- (id)description;

@end

#endif /* XCSynthesizedEventRecord_h */
