//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "XCDebugLogDelegate.h"
#import "XCTASDebugLogDelegate.h"

@class NSMutableArray, NSObject<OS_dispatch_queue>, NSString;

@interface XCTDefaultDebugLogHandler : NSObject <XCTASDebugLogDelegate, XCDebugLogDelegate>
{
    id <XCDebugLogDelegate> _logSink;
    NSMutableArray *_debugMessageBuffer;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (id)sharedHandler;
- (void).cxx_destruct;
@property(readonly) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(readonly) NSMutableArray *debugMessageBuffer; // @synthesize debugMessageBuffer=_debugMessageBuffer;
@property(retain) id <XCDebugLogDelegate> logSink; // @synthesize logSink=_logSink;
- (void)logDebugMessage:(id)arg1;
- (void)_queue_flushDebugMessageBufferWithBlock:(CDUnknownBlockType)arg1;
- (void)printBufferedDebugMessages;
- (void)logStartupInfo;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

