//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary;

@interface XCTMeasureOptions : NSObject
{
    _Bool _enableParallelizedSampling;
    _Bool _scheduleKickOffOnNewThread;
    _Bool _allowContinuousSampling;
    _Bool _discardTraceIteration;
    _Bool _discardFirstIteration;
    _Bool _traceCollectionEnabled;
    unsigned long long _invocationOptions;
    unsigned long long _iterationCount;
    NSDictionary *_performanceTestConfiguration;
    double _quiesceCpuIdlePercent;
    double _quiesceCpuIdleTimeLimit;
}

+ (id)defaultOptions;
- (void).cxx_destruct;
@property(nonatomic) double quiesceCpuIdleTimeLimit; // @synthesize quiesceCpuIdleTimeLimit=_quiesceCpuIdleTimeLimit;
@property(nonatomic) double quiesceCpuIdlePercent; // @synthesize quiesceCpuIdlePercent=_quiesceCpuIdlePercent;
@property(nonatomic) _Bool traceCollectionEnabled; // @synthesize traceCollectionEnabled=_traceCollectionEnabled;
@property(nonatomic) _Bool discardFirstIteration; // @synthesize discardFirstIteration=_discardFirstIteration;
@property(retain, nonatomic) NSDictionary *performanceTestConfiguration; // @synthesize performanceTestConfiguration=_performanceTestConfiguration;
@property(nonatomic) _Bool discardTraceIteration; // @synthesize discardTraceIteration=_discardTraceIteration;
@property(nonatomic) _Bool allowContinuousSampling; // @synthesize allowContinuousSampling=_allowContinuousSampling;
@property(nonatomic) unsigned long long iterationCount; // @synthesize iterationCount=_iterationCount;
@property(nonatomic) unsigned long long invocationOptions; // @synthesize invocationOptions=_invocationOptions;
@property(readonly, nonatomic) unsigned long long instrumentAutomatic;
@property(nonatomic) _Bool allowConcurrentIterations;
- (void)applyPerformanceTestConfiguration;
@property(readonly, nonatomic) NSDictionary *instrumentOptions;
- (id)initWithInstrumentOptionsDictionary:(id)arg1;
- (id)init;

@end

