//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <XCTest/XCTIssue.h>

@class NSArray, NSDate, NSError, NSMutableArray, NSString, XCTSourceCodeContext;

@interface XCTMutableIssue : XCTIssue
{
    NSMutableArray *_mutableAttachments;
}

- (void).cxx_destruct;
- (void)addAttachment:(id)arg1;
@property(copy) NSArray *attachments;
- (id)initWithType:(long long)arg1 compactDescription:(id)arg2 detailedDescription:(id)arg3 sourceCodeContext:(id)arg4 associatedError:(id)arg5 attachments:(id)arg6;

// Remaining properties
@property(retain) NSError *associatedError; // @dynamic associatedError;
@property(copy) NSString *compactDescription; // @dynamic compactDescription;
@property(copy) NSString *detailedDescription; // @dynamic detailedDescription;
@property(retain) XCTSourceCodeContext *sourceCodeContext; // @dynamic sourceCodeContext;
@property(copy) NSDate *timestamp; // @dynamic timestamp;
@property long long type; // @dynamic type;

@end

