//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSArray, XCTPerformanceMeasurementTimestamp;

@protocol XCTMetric <NSCopying, NSObject>
- (NSArray *)reportMeasurementsFromStartTime:(XCTPerformanceMeasurementTimestamp *)arg1 toEndTime:(XCTPerformanceMeasurementTimestamp *)arg2 error:(id *)arg3;

@optional
- (void)didStopMeasuring;
- (void)willBeginMeasuring;
@end

