//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSURL;

@interface XCTSourceCodeLocation : NSObject <NSSecureCoding>
{
    NSURL *_fileURL;
    long long _lineNumber;
}

+ (_Bool)supportsSecureCoding;
- (void).cxx_destruct;
@property(readonly) long long lineNumber; // @synthesize lineNumber=_lineNumber;
@property(readonly) NSURL *fileURL; // @synthesize fileURL=_fileURL;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)description;
- (id)initWithFilePath:(id)arg1 lineNumber:(long long)arg2;
- (id)initWithFileURL:(id)arg1 lineNumber:(long long)arg2;

@end

