//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSError, XCTSourceCodeSymbolInfo;

@interface XCTSourceCodeFrame : NSObject <NSSecureCoding>
{
    XCTSourceCodeSymbolInfo *_frameSymbolInfo;
    unsigned long long _address;
    NSError *_symbolicationError;
}

+ (_Bool)supportsSecureCoding;
- (void).cxx_destruct;
@property(readonly) NSError *symbolicationError; // @synthesize symbolicationError=_symbolicationError;
@property(readonly) unsigned long long address; // @synthesize address=_address;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
@property(readonly) XCTSourceCodeSymbolInfo *symbolInfo;
- (id)symbolInfoWithError:(id *)arg1;
- (id)description;
- (id)initWithAddress:(unsigned long long)arg1;
- (id)initWithAddress:(unsigned long long)arg1 symbolInfo:(id)arg2;

@end

