//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "XCUIEventConverting.h"

@class NSString;

@interface XCUITouchBarEventConverter : NSObject <XCUIEventConverting>
{
}

+ (id)supportedEventTypes;
- (id)interpolatorForPointerEvent:(id)arg1 eventSource:(struct __CGEventSource *)arg2;
- (id)interpolationStepperForPointerEvent:(id)arg1 eventSource:(struct __CGEventSource *)arg2;
- (BOOL)shouldInterpolatePointerEvent:(id)arg1;
- (id)_touchBarEventForCGEventType:(unsigned int)arg1 atLocation:(struct CGPoint)arg2 error:(id *)arg3;
- (id)cgEventForPointerEvent:(id)arg1 waitForConfirmation:(char *)arg2 error:(id *)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

