//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol XCUIEventDispatching <NSObject>
@property(retain) id <XCUIEventGeneratorRequest> currentRequest;
@property(readonly) struct __CGEventSource *eventSource;
- (void)postCGEvent:(struct __CGEvent *)arg1 forRequest:(id <XCUIEventGeneratorRequest>)arg2 waitForConfirmation:(BOOL)arg3;
@end

