//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class XCUIAccessibilityInterface, XCUIApplicationMonitor, XCUIEventSynthesizing, XCUIApplicationManaging;
@class XCUIDeviceEventAndStateInterface, XCUIApplicationAutomationSessionProviding, XCUIScreenDataSource;
@class XCUIResetAuthorizationStatusOfProtectedResourcesInterface, XCUIDeviceDiagnostics, XCUIInterruptionMonitoring;
@class XCUIXcodeApplicationManaging;

@class NSString, XCUIRemote, XCUISiriService;

@interface XCUIDevice ()
{
    _Bool _isLocal;
    _Bool _isSimulatorDevice;
    long long _platform;
    XCUIAccessibilityInterface *_accessibilityInterface;
    XCUIApplicationMonitor *_applicationMonitor;
    XCUIEventSynthesizing *_eventSynthesizer;
    XCUIApplicationManaging *_platformApplicationManager;
    XCUIXcodeApplicationManaging *_xcodeApplicationManager;
    XCUIDeviceEventAndStateInterface *_deviceEventAndStateInterface;
    XCUIApplicationAutomationSessionProviding *_applicationAutomationSessionProvider;
    XCUISiriService *_siriService;
    XCUIScreenDataSource *_screenDataSource;
    NSString *_uniqueIdentifier;
    XCUIRemote *_remote;
    XCUIInterruptionMonitoring *_interruptionMonitor;
    XCUIResetAuthorizationStatusOfProtectedResourcesInterface *_resetAuthorizationStatusInterface;
    XCUIDeviceDiagnostics *_diagnosticsProvider;
}

//+ (id)sharedDevice;
+ (void)setLocalDevice:(id)arg1;
+ (id)localDevice;
//- (void).cxx_destruct;
- (id)diagnosticsProvider;
- (id)resetAuthorizationStatusInterface;
- (id)interruptionMonitor;
- (id)remote;
- (_Bool)isSimulatorDevice;
- (id)uniqueIdentifier;
- (id)screenDataSource;
- (id)applicationAutomationSessionProvider;
- (id)deviceEventAndStateInterface;
- (id)xcodeApplicationManager;
- (id)platformApplicationManager;
- (id)eventSynthesizer;
- (id)applicationMonitor;
- (id)accessibilityInterface;
- (long long)platform;
- (_Bool)isLocal;
- (void)remoteAutomationSessionDidDisconnect:(id)arg1;
- (void)attachLocalizableStringsData;
- (void)rotateDigitalCrown:(double)arg1 velocity:(double)arg2;
- (void)pressLockButton;
- (void)holdHomeButtonForDuration:(double)arg1;
//- (void)pressButton:(long long)arg1;
- (void)_silentPressButton:(long long)arg1;
- (void)_setOrientation:(long long)arg1;
//@property(nonatomic) long long orientation;
- (id)init;
- (id)description;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)spindumpAttachmentForProcessID:(int)arg1 error:(id *)arg2;
- (id)makeDiagnosticScreenshotAttachmentForDevice;
- (id)mainScreen;
- (id)screens;
- (id)mainScreenOrError:(id *)arg1;
- (id)screensOrError:(id *)arg1;
//@property(readonly) XCUISiriService *siriService; // @synthesize siriService=_siriService;
- (_Bool)supportsPressureInteraction;
- (_Bool)performDeviceEvent:(id)arg1 error:(id *)arg2;
- (_Bool)configuredForUITesting;
- (id)diagnosticAttachmentsForError:(id)arg1;
- (id)initWithDiagnosticProvider:(id)arg1;
- (id)initLocalDeviceWithPlatform:(long long)arg1;

@end

