//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XCUIEventSynthesisRequest.h"

@class NSString, XCSynthesizedEventRecord;

@interface XCUIDeviceRemoteAutomationSessionEventRequest : NSObject <XCUIEventSynthesisRequest>
{
    XCSynthesizedEventRecord *_event;
    double _upperBoundOnDuration;
}

@property double upperBoundOnDuration; // @synthesize upperBoundOnDuration=_upperBoundOnDuration;
@property(readonly) XCSynthesizedEventRecord *event; // @synthesize event=_event;
- (void).cxx_destruct;
- (void)invalidate;
- (id)initWithEvent:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

