//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XCTElementSetTransformer-Protocol.h"

@class XCTElementSetTransformer;
@class XCTElementSnapshotAttributeDataSource;

@class NSArray, NSOrderedSet, NSSet, NSString, XCElementSnapshot, XCUIApplication, XCUIElement;

@interface XCUIElementQuery ()
{
    _Bool _changesScope;
    _Bool _stopsOnFirstMatch;
    _Bool _modalViewPruningDisabled;
    XCUIElementQuery *_inputQuery;
    NSSet *_expressedTypes;
    NSArray *_expressedIdentifiers;
    NSOrderedSet *_lastInput;
    NSOrderedSet *_lastOutput;
    XCElementSnapshot *_rootElementSnapshot;
    NSString *_queryDescription;
    id <XCTElementSetTransformer> _transformer;
}

//- (void).cxx_destruct;
@property(retain) id <XCTElementSetTransformer> transformer; // @synthesize transformer=_transformer;
@property(readonly, copy) NSString *queryDescription; // @synthesize queryDescription=_queryDescription;
@property(retain) XCElementSnapshot *rootElementSnapshot; // @synthesize rootElementSnapshot=_rootElementSnapshot;
@property _Bool modalViewPruningDisabled; // @synthesize modalViewPruningDisabled=_modalViewPruningDisabled;
@property(copy) NSOrderedSet *lastOutput; // @synthesize lastOutput=_lastOutput;
@property(copy) NSOrderedSet *lastInput; // @synthesize lastInput=_lastInput;
@property(copy) NSArray *expressedIdentifiers; // @synthesize expressedIdentifiers=_expressedIdentifiers;
@property(copy) NSSet *expressedTypes; // @synthesize expressedTypes=_expressedTypes;
@property _Bool stopsOnFirstMatch; // @synthesize stopsOnFirstMatch=_stopsOnFirstMatch;
@property _Bool changesScope; // @synthesize changesScope=_changesScope;
@property(readonly) XCUIElementQuery *inputQuery; // @synthesize inputQuery=_inputQuery;
@property(copy) XCUIElementQuery *statusItems;
@property(copy) XCUIElementQuery *otherElements;
@property(copy) XCUIElementQuery *handles;
@property(copy) XCUIElementQuery *layoutItems;
@property(copy) XCUIElementQuery *layoutAreas;
@property(copy) XCUIElementQuery *cells;
@property(copy) XCUIElementQuery *levelIndicators;
@property(copy) XCUIElementQuery *grids;
@property(copy) XCUIElementQuery *rulerMarkers;
@property(copy) XCUIElementQuery *rulers;
@property(copy) XCUIElementQuery *dockItems;
@property(copy) XCUIElementQuery *mattes;
@property(copy) XCUIElementQuery *helpTags;
@property(copy) XCUIElementQuery *colorWells;
@property(copy) XCUIElementQuery *relevanceIndicators;
@property(copy) XCUIElementQuery *splitters;
@property(copy) XCUIElementQuery *splitGroups;
@property(copy) XCUIElementQuery *valueIndicators;
@property(copy) XCUIElementQuery *ratingIndicators;
@property(copy) XCUIElementQuery *timelines;
@property(copy) XCUIElementQuery *decrementArrows;
@property(copy) XCUIElementQuery *incrementArrows;
@property(copy) XCUIElementQuery *steppers;
@property(copy) XCUIElementQuery *webViews;
@property(copy) XCUIElementQuery *maps;
@property(copy) XCUIElementQuery *menuBarItems;
@property(copy) XCUIElementQuery *menuBars;
@property(copy) XCUIElementQuery *menuItems;
@property(copy) XCUIElementQuery *menus;
@property(copy) XCUIElementQuery *textViews;
@property(copy) XCUIElementQuery *datePickers;
@property(copy) XCUIElementQuery *secureTextFields;
@property(copy) XCUIElementQuery *textFields;
@property(copy) XCUIElementQuery *staticTexts;
@property(copy) XCUIElementQuery *scrollBars;
@property(copy) XCUIElementQuery *scrollViews;
@property(copy) XCUIElementQuery *searchFields;
@property(copy) XCUIElementQuery *icons;
@property(copy) XCUIElementQuery *images;
@property(copy) XCUIElementQuery *links;
@property(copy) XCUIElementQuery *toggles;
@property(copy) XCUIElementQuery *switches;
@property(copy) XCUIElementQuery *pickerWheels;
@property(copy) XCUIElementQuery *pickers;
@property(copy) XCUIElementQuery *segmentedControls;
@property(copy) XCUIElementQuery *activityIndicators;
@property(copy) XCUIElementQuery *progressIndicators;
@property(copy) XCUIElementQuery *pageIndicators;
@property(copy) XCUIElementQuery *sliders;
@property(copy) XCUIElementQuery *collectionViews;
@property(copy) XCUIElementQuery *browsers;
@property(copy) XCUIElementQuery *disclosedChildRows;
@property(copy) XCUIElementQuery *outlineRows;
@property(copy) XCUIElementQuery *outlines;
@property(copy) XCUIElementQuery *tableColumns;
@property(copy) XCUIElementQuery *tableRows;
@property(copy) XCUIElementQuery *tables;
@property(copy) XCUIElementQuery *statusBars;
@property(copy) XCUIElementQuery *toolbars;
@property(copy) XCUIElementQuery *tabGroups;
@property(copy) XCUIElementQuery *tabBars;
@property(copy) XCUIElementQuery *tabs;
@property(copy) XCUIElementQuery *navigationBars;
@property(copy) XCUIElementQuery *keys;
@property(copy) XCUIElementQuery *keyboards;
@property(copy) XCUIElementQuery *popovers;
@property(copy) XCUIElementQuery *toolbarButtons;
@property(copy) XCUIElementQuery *menuButtons;
@property(copy) XCUIElementQuery *comboBoxes;
@property(copy) XCUIElementQuery *popUpButtons;
@property(copy) XCUIElementQuery *disclosureTriangles;
@property(copy) XCUIElementQuery *checkBoxes;
@property(copy) XCUIElementQuery *radioGroups;
@property(copy) XCUIElementQuery *radioButtons;
@property(copy) XCUIElementQuery *buttons;
@property(copy) XCUIElementQuery *dialogs;
@property(copy) XCUIElementQuery *bannerNotifications;
@property(copy) XCUIElementQuery *alerts;
@property(copy) XCUIElementQuery *drawers;
@property(copy) XCUIElementQuery *sheets;
@property(copy) XCUIElementQuery *windows;
@property(copy) XCUIElementQuery *groups;
@property(copy) XCUIElementQuery *touchBars;
- (id)snapshotForElement:(id)arg1 attributes:(id)arg2 parameters:(id)arg3 timeoutControls:(id)arg4 error:(id *)arg5;
- (_Bool)_resolveRemoteElements:(id)arg1 inSnapshot:(id)arg2 query:(id)arg3 runtimeIssues:(id *)arg4 error:(id *)arg5;
- (id)elementSnapshotForDebugDescriptionWithNoMatchesMessage:(id *)arg1;
- (id)_matchingSnapshotsForLocallyEvaluatedQuery:(id)arg1 error:(id *)arg2;
- (id)_matchingSnapshotsForRemotelyEvaluatedQuery:(id)arg1 error:(id *)arg2;
- (id)_executeWithError:(id *)arg1;
- (id)allMatchingSnapshotsWithError:(id *)arg1;
- (id)uniqueMatchingSnapshotWithError:(id *)arg1;
@property(readonly) XCTElementSnapshotAttributeDataSource *elementSnapshotAttributeDataSource;
- (id)backingQueryWithError:(id *)arg1;
@property(copy) XCUIElementQuery *excludingNonModalElements;
@property(copy) XCUIElementQuery *includingNonModalElements;
@property(copy) NSArray *allElementsBoundByIndex;
@property(copy) NSArray *allElementsBoundByAccessibilityElement;
- (id)_elementMatchingAccessibilityElementOfSnapshot:(id)arg1;
- (id)_descendantMatchingAccessibilityElement:(id)arg1;
//- (id)objectForKeyedSubscript:(id)arg1;
//- (id)elementMatchingType:(unsigned long long)arg1 identifier:(id)arg2;
@property XCUIElement *firstMatch;
- (id)elementWithPlaceholderValue:(id)arg1;
- (id)elementWithValue:(id)arg1;
- (id)elementWithIdentifier:(id)arg1;
- (id)elementWithLabel:(id)arg1;
- (id)elementWithTitle:(id)arg1;
//- (id)elementMatchingPredicate:(id)arg1;
//- (id)elementBoundByIndex:(unsigned long long)arg1;
//- (id)elementAtIndex:(unsigned long long)arg1;
@property XCUIElement *element;
//- (id)containingType:(unsigned long long)arg1 identifier:(id)arg2;
//- (id)containingPredicate:(id)arg1;
- (id)_containingPredicate:(id)arg1 queryDescription:(id)arg2;
//- (id)matchingIdentifier:(id)arg1;
//- (id)matchingType:(unsigned long long)arg1 identifier:(id)arg2;
//- (id)matchingPredicate:(id)arg1;
- (id)_predicateWithType:(unsigned long long)arg1 identifier:(id)arg2;
- (id)_queryWithPredicate:(id)arg1;
- (id)_queryWithPredicate:(id)arg1 description:(id)arg2;
- (id)sorted:(CDUnknownBlockType)arg1;
- (id)descending:(unsigned long long)arg1;
- (id)ascending:(unsigned long long)arg1;
- (id)filter:(CDUnknownBlockType)arg1;
- (id)_childrenMatchingTypes:(id)arg1;
//- (id)childrenMatchingType:(unsigned long long)arg1;
- (id)_descendantsMatchingTypes:(id)arg1;
- (id)_descendantsMatchingPredicate:(id)arg1;
//- (id)descendantsMatchingType:(unsigned long long)arg1;
- (id)debugDescriptionWithSnapshot:(id)arg1;
@property(copy) NSString *debugDescription;
- (id)_debugDescriptionWithIndent:(id *)arg1 rootElementSnapshot:(id)arg2;
@property(readonly, copy) NSString *elementDescription;
- (id)_derivedExpressedIdentifiers;
- (id)_derivedExpressedTypes;
@property(readonly, copy) NSSet *allExpressedTypes;
@property(readonly) XCUIApplication *application;
- (id)device;
//@property unsigned long long count;
- (id)initWithInputQuery:(id)arg1 queryDescription:(id)arg2 transformer:(id)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

