//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, XCUIElement;

@protocol XCUIInterruptionMonitoring <NSObject>
@property _Bool didHandleUIInterruption;
- (_Bool)handleInterruptingElement:(XCUIElement *)arg1;
- (void)removeInterruptionHandlerWithIdentifier:(id <NSObject>)arg1;
- (id <NSObject>)addInterruptionHandlerWithDescription:(NSString *)arg1 block:(_Bool (^)(XCUIElement *))arg2;
@end

