//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class XCUIApplicationProcess;

@protocol XCUIApplicationProcessDelegate <NSObject>
- (void)applicationProcessAutomationSessionRequestFailed:(XCUIApplicationProcess *)arg1;
- (_Bool)applicationProcessShouldRequestAutomationSession:(XCUIApplicationProcess *)arg1;
@end

