//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XCUIEventIterating.h"

@class NSEnumerator, NSString, XCPointerEventPath, XCUIContinuousEventInterpolationStepper;

@interface XCUIEventIterator : NSObject <XCUIEventIterating>
{
    NSEnumerator *_eventEnumerator;
    XCUIContinuousEventInterpolationStepper *_eventInterpolator;
    double _startTime;
    XCPointerEventPath *_eventPath;
    struct __CGEventSource *_eventSource;
    id <XCUIEventConverting> _eventConverter;
}

@property(readonly) id <XCUIEventConverting> eventConverter; // @synthesize eventConverter=_eventConverter;
@property(readonly) struct __CGEventSource *eventSource; // @synthesize eventSource=_eventSource;
@property(readonly) XCPointerEventPath *eventPath; // @synthesize eventPath=_eventPath;
- (void).cxx_destruct;
- (id)nextEvent:(double *)arg1 waitForConfirmation:(char *)arg2 error:(id *)arg3;
- (id)initWithEventPath:(id)arg1 eventSource:(struct __CGEventSource *)arg2;
- (id)initWithEventPath:(id)arg1 eventSource:(struct __CGEventSource *)arg2 eventConverter:(id)arg3;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

