//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "XCUIPlatformApplicationServicesProviding.h"

@class NSObject<OS_dispatch_queue>, NSString;

@interface XCUILaunchServicesMonitor : NSObject <XCUIPlatformApplicationServicesProviding>
{
    // Error parsing type: AQ, name: _nextEventID
    id <XCUIApplicationPlatformServicesProviderDelegate> platformApplicationServicesProviderDelegate;
    void *_notificationID;
    id <XCUILaunchServicesFramework> _launchServicesFramework;
    NSObject<OS_dispatch_queue> *_queue;
}

@property(retain) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain) id <XCUILaunchServicesFramework> launchServicesFramework; // @synthesize launchServicesFramework=_launchServicesFramework;
@property void *notificationID; // @synthesize notificationID=_notificationID;
@property __weak id <XCUIApplicationPlatformServicesProviderDelegate> platformApplicationServicesProviderDelegate; // @synthesize platformApplicationServicesProviderDelegate;
- (void).cxx_destruct;
- (void)launchApplicationWithPath:(id)arg1 bundleID:(id)arg2 arguments:(id)arg3 environment:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)terminateApplicationWithBundleID:(id)arg1 pid:(int)arg2 completion:(CDUnknownBlockType)arg3;
- (void)requestApplicationSpecifierForPID:(int)arg1 reply:(CDUnknownBlockType)arg2;
- (struct __LSASN *)_ASNForPid:(int)arg1;
- (void)beginMonitoringApplicationWithSpecifier:(id)arg1;
- (struct __LSASN *)_ASNForBundleID:(id)arg1 path:(id)arg2;
- (void)_updateApplicationWithASN:(struct __LSASN *)arg1 eventID:(unsigned long long)arg2;
- (BOOL)_frontUIApplicationMatchesASN:(struct __LSASN *)arg1;
- (BOOL)_frontApplicationMatchesASN:(struct __LSASN *)arg1;
- (void)_handleLSNotification:(int)arg1 appInfo:(id)arg2 eventID:(unsigned long long)arg3;
- (unsigned long long)_nextNotificationEventID;
- (id)init;
- (id)initWithLaunchServicesFramework:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

