//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XCUIScreenDataSource.h"

@class NSString;

@interface XCUILocalDeviceScreenDataSource : NSObject <XCUIScreenDataSource>
{
}

- (id)HEICData:(struct CGImage *)arg1 compressionQuality:(double)arg2;
- (id)_clippedScreenshotData:(id)arg1 compressionQuality:(double)arg2 rect:(struct CGRect)arg3 scale:(double)arg4;
- (void)requestScreenshotOfScreenWithID:(long long)arg1 withRect:(struct CGRect)arg2 scale:(double)arg3 formatUTI:(id)arg4 compressionQuality:(double)arg5 withReply:(CDUnknownBlockType)arg6;
- (void)requestScaleForScreenWithIdentifier:(long long)arg1 completion:(CDUnknownBlockType)arg2;
- (void)requestScreenIdentifiersWithCompletion:(CDUnknownBlockType)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

