//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface XCUIApplicationImplDepot : NSObject
{
    NSMutableDictionary *_applicationImpls;
    id <XCUIDevice> _device;
}

- (void).cxx_destruct;
@property(readonly) id <XCUIDevice> device; // @synthesize device=_device;
- (id)applicationImplForSpecifier:(id)arg1;
- (id)_canonicalSpecifierFromSpecifier:(id)arg1;
- (id)_identifierFromSpecifier:(id)arg1;
- (id)initWithDevice:(id)arg1;

@end

