//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XCUIIPhoneOSDevice.h"

@protocol XCUIIOSDevice <XCUIIPhoneOSDevice>
@property(nonatomic) long long orientation;
- (void)pressLockButton;
- (void)holdHomeButtonForDuration:(double)arg1;
- (void)pressButton:(long long)arg1;
@end

