//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "XCUIDeviceRemoteDaemonConnectionProviding.h"

@class NSString;

@interface XCUIDeviceRemoteDaemonConnectionProvider : NSObject <XCUIDeviceRemoteDaemonConnectionProviding>
{
    CDUnknownBlockType _dtxConnectionProviderFactory;
}

+ (id)connectionProviderForMobileDeviceWithIdentifier:(id)arg1;
+ (id)connectionProviderForSimDevice:(id)arg1;
+ (Class)XCTProtocolVersionClass;
+ (Class)XCTMobileDeviceDTXConnectionProviderClass;
+ (Class)XCTSimulatorDeviceDTXConnectionProviderClass;
+ (Class)XCTDaemonProxyProviderClass;
+ (void)initialize;
+ (void)setSoftlinkFrameworksError:(id)arg1;
+ (id)softlinkFrameworksError;
@property(readonly) CDUnknownBlockType dtxConnectionProviderFactory; // @synthesize dtxConnectionProviderFactory=_dtxConnectionProviderFactory;
- (void).cxx_destruct;
- (void)makeNewDaemonConnectionWithCompletion:(CDUnknownBlockType)arg1;
- (id)initWithDTXConnectionProviderFactory:(CDUnknownBlockType)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

