//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString, XCUIScreen, XCUITestContext;

@protocol XCUIDevice <NSObject>
@property(readonly) XCUITestContext *testContext;
@property(readonly) NSString *uniqueIdentifier;
@property(readonly) _Bool isLocal;
@property(readonly, copy) NSArray *screens;
@property(readonly) XCUIScreen *mainScreen;
@property(readonly) long long platform;
@property(readonly) id <XCUIScreenDataSource> screenDataSource;
@property(readonly) id <XCUIApplicationAutomationSessionProviding> applicationAutomationSessionProvider;
@property(readonly) id <XCUIDeviceEventAndStateInterface> deviceEventAndStateInterface;
@property(readonly) id <XCUIApplicationManaging> platformApplicationManager;
@property(readonly) id <XCUIXcodeApplicationManaging> xcodeApplicationManager;
@property(readonly) id <XCUIApplicationMonitor> applicationMonitor;
@property(readonly) id <XCUIAccessibilityInterface> accessibilityInterface;
@property(readonly) id <XCUIEventSynthesizing> eventSynthesizer;
- (NSArray *)screensOrError:(id *)arg1;
- (XCUIScreen *)mainScreenOrError:(id *)arg1;
@end

