//
//  AXSettings.h
//  WebDriverAgent
//
//  Created by Kazuaki Matsuo on 2019/08/21.
//  Copyright © 2019 Facebook. All rights reserved.
//

/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AccessibilityUtilities.framework/AccessibilityUtilities
 */

@interface AXSettings : NSObject

@property bool reduceMotionEnabled;

+ (id)sharedInstance;

- (void)setReduceMotionEnabled:(bool)arg1;
- (bool)reduceMotionEnabled;

@end
