# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-12

    env:
      XCODE_VERSION: 14.2

      # Real devices
      ZIP_PKG_NAME_IOS: "WebDriverAgentRunner-Runner.zip"
      PKG_PATH_IOS: "appium_wda_ios"
      ZIP_PKG_NAME_TVOS: "WebDriverAgentRunner_tvOS-Runner.zip"
      PKG_PATH_TVOS: "appium_wda_tvos"

      # Simulator - x86_64
      ZIP_PKG_NAME_IOS_SIM_X86_64: "WebDriverAgentRunner-Build-Sim-x86-64.zip"
      PKG_PATH_IOS_SIM_X86_64: "appium_wda_ios_sim_x86_64"
      ZIP_PKG_NAME_TVOS_SIM_X86_64: "WebDriverAgentRunner_tvOS-Build-Sim-x86-64.zip"
      PKG_PATH_TVOS_SIM_X86_64: "appium_wda_tvos_sim_x86_64"

      # Simulator - arm64
      ZIP_PKG_NAME_IOS_SIM_ARM64: "WebDriverAgentRunner-Build-Sim-arm64.zip"
      PKG_PATH_IOS_SIM_ARM64: "appium_wda_ios_sim_arm64"
      ZIP_PKG_NAME_TVOS_SIM_ARM64: "WebDriverAgentRunner_tvOS-Build-Sim-arm64.zip"
      PKG_PATH_TVOS_SIM_ARM64: "appium_wda_tvos_sim_arm64"

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: lts/*
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "${{ env.XCODE_VERSION }}"
    - run: npm install --no-package-lock
      name: Install dev dependencies
    - run: npm run build
      name: Run build
    - run: npm run test
      name: Run test

    # building WDA packages for real devices
    - name: Build iOS
      run: |
        xcodebuild clean build-for-testing \
          -project WebDriverAgent.xcodeproj \
          -derivedDataPath $PKG_PATH_IOS \
          -scheme WebDriverAgentRunner \
          -destination generic/platform=iOS \
          CODE_SIGNING_ALLOWED=NO ARCHS=arm64

    - name: Creating a zip of WebDriverAgentRunner-Runner.app for iOS
      run: |
        pushd appium_wda_ios/Build/Products/Debug-iphoneos
        zip -r $ZIP_PKG_NAME_IOS WebDriverAgentRunner-Runner.app
        popd
        mv $PKG_PATH_IOS/Build/Products/Debug-iphoneos/$ZIP_PKG_NAME_IOS ./
    - name: Build tvOS
      run: |
        xcodebuild clean build-for-testing \
          -project WebDriverAgent.xcodeproj \
          -derivedDataPath $PKG_PATH_TVOS \
          -scheme WebDriverAgentRunner_tvOS \
          -destination generic/platform=tvOS \
          CODE_SIGNING_ALLOWED=NO ARCHS=arm64
    - name: Creating a zip of WebDriverAgentRunner-Runner.app for tvOS
      run: |
        pushd appium_wda_tvos/Build/Products/Debug-appletvos
        zip -r $ZIP_PKG_NAME_TVOS WebDriverAgentRunner_tvOS-Runner.app
        popd
        mv $PKG_PATH_TVOS/Build/Products/Debug-appletvos/$ZIP_PKG_NAME_TVOS ./

    # building WDA packages for x86_64
    - name: Build iOS for simulator for x86_64
      run: |
        xcodebuild clean build-for-testing \
          -project WebDriverAgent.xcodeproj \
          -derivedDataPath $PKG_PATH_IOS_SIM_X86_64 \
          -scheme WebDriverAgentRunner \
          -destination "$DESTI_IOS_SIM" \
          CODE_SIGNING_ALLOWED=NO ARCHS=x86_64

    - name: Creating a zip of WebDriverAgentRunner-Build-Sim for iOS
      run: |
        pushd $PKG_PATH_IOS_SIM_X86_64
        zip -r $ZIP_PKG_NAME_IOS_SIM_X86_64 Build
        popd
        mv $PKG_PATH_IOS_SIM_X86_64/$ZIP_PKG_NAME_IOS_SIM_X86_64 ./
    - name: Build tvOS for simulator for x86_64
      run: |
        xcodebuild clean build-for-testing \
          -project WebDriverAgent.xcodeproj \
          -derivedDataPath $PKG_PATH_TVOS_SIM_X86_64 \
          -scheme WebDriverAgentRunner_tvOS \
          -destination "$DESTI_TVOS_SIM" \
          CODE_SIGNING_ALLOWED=NO ARCHS=x86_64
    - name: Creating a zip of WebDriverAgentRunner-Build-Sim for iOS
      run: |
        pushd $PKG_PATH_TVOS_SIM_X86_64
        zip -r $ZIP_PKG_NAME_TVOS_SIM_X86_64 Build
        popd
        mv $PKG_PATH_TVOS_SIM_X86_64/$ZIP_PKG_NAME_TVOS_SIM_X86_64 ./

    # building WDA packages for arm64
    - name: Build iOS for simulator for arm64
      run: |
        xcodebuild clean build-for-testing \
          -project WebDriverAgent.xcodeproj \
          -derivedDataPath $PKG_PATH_IOS_SIM_ARM64 \
          -scheme WebDriverAgentRunner \
          -destination "$DESTI_IOS_SIM" \
          CODE_SIGNING_ALLOWED=NO ARCHS=arm64

    - name: Creating a zip of WebDriverAgentRunner-Build-Sim for iOS
      run: |
        pushd $PKG_PATH_IOS_SIM_ARM64
        zip -r $ZIP_PKG_NAME_IOS_SIM_ARM64 Build
        popd
        mv $PKG_PATH_IOS_SIM_ARM64/$ZIP_PKG_NAME_IOS_SIM_ARM64 ./

    - name: Build tvOS for simulator for arm64
      run: |
        xcodebuild clean build-for-testing \
          -project WebDriverAgent.xcodeproj \
          -derivedDataPath $PKG_PATH_TVOS_SIM_ARM64 \
          -scheme WebDriverAgentRunner_tvOS \
          -destination "$DESTI_TVOS_SIM" \
          CODE_SIGNING_ALLOWED=NO ARCHS=arm64
    - name: Creating a zip of WebDriverAgentRunner-Build-Sim for iOS
      run: |
        pushd $PKG_PATH_TVOS_SIM_ARM64
        zip -r $ZIP_PKG_NAME_TVOS_SIM_ARM64 Build
        popd
        mv $PKG_PATH_TVOS_SIM_ARM64/$ZIP_PKG_NAME_TVOS_SIM_ARM64 ./

    # release tasks - all packages
    - run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      name: Release
