# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-13

    env:
      XCODE_VERSION: 14.3.1
      PKG_PATH_IOS: "appium_wda_ios"
      PKG_PATH_TVOS: "appium_wda_tvos"

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: lts/*
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "${{ env.XCODE_VERSION }}"
    - run: npm install --no-package-lock
      name: Install dev dependencies
    - run: npm run build
      name: Run build
    - run: npm run test
      name: Run test

    # building WDA packages to test package build
    - name: Build iOS
      run: |
        xcodebuild clean build-for-testing \
          -project WebDriverAgent.xcodeproj \
          -derivedDataPath $PKG_PATH_IOS \
          -scheme WebDriverAgentRunner \
          -destination generic/platform=iOS \
          CODE_SIGNING_ALLOWED=NO ARCHS=arm64
    - name: Build tvOS
      run: |
        xcodebuild clean build-for-testing \
          -project WebDriverAgent.xcodeproj \
          -derivedDataPath $PKG_PATH_TVOS \
          -scheme WebDriverAgentRunner_tvOS \
          -destination generic/platform=tvOS \
          CODE_SIGNING_ALLOWED=NO ARCHS=arm64

    # release tasks
    - run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      name: Release
