name: Building WebDriverAgent

on:
  workflow_dispatch:

jobs:
  build:
    name: Build WDA for real iOS and tvOS devices
    runs-on: macos-12

    env:
      XCODE_VERSION: 14.2
      ZIP_PKG_NAME_IOS: "WebDriverAgentRunner-Runner.zip"
      PKG_PATH_IOS: "appium_wda_ios"
      ZIP_PKG_NAME_TVOS: "WebDriverAgentRunner_tvOS-Runner.zip"
      PKG_PATH_TVOS: "appium_wda_tvos"

      ZIP_PKG_NAME_IOS_SIM: "WebDriverAgentRunner-Build-Sim.zip"
      PKG_PATH_IOS_SIM: "appium_wda_ios_sim"
      ZIP_PKG_NAME_TVOS_SIM: "WebDriverAgentRunner_tvOS-Build-Sim.zip"
      PKG_PATH_TVOS_SIM: "appium_wda_tvos_sim"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "${{ env.XCODE_VERSION }}"
      - name: Build iOS
        run: |
          xcodebuild clean build-for-testing \
            -project WebDriverAgent.xcodeproj \
            -derivedDataPath $PKG_PATH_IOS \
            -scheme WebDriverAgentRunner \
            -destination generic/platform=iOS \
            CODE_SIGNING_ALLOWED=NO ARCHS=arm64
      - name: Creating a zip of WebDriverAgentRunner-Runner.app for iOS
        run: |
          pushd $PKG_PATH_IOS/Build/Products/Debug-iphoneos
          zip -r $ZIP_PKG_NAME_IOS WebDriverAgentRunner-Runner.app
          popd
          mv $PKG_PATH_IOS/Build/Products/Debug-iphoneos/$ZIP_PKG_NAME_IOS ./
      - name: Build tvOS
        run: |
          xcodebuild clean build-for-testing \
            -project WebDriverAgent.xcodeproj \
            -derivedDataPath $PKG_PATH_TVOS \
            -scheme WebDriverAgentRunner_tvOS \
            -destination generic/platform=tvOS \
            CODE_SIGNING_ALLOWED=NO ARCHS=arm64
      - name: Creating a zip of WebDriverAgentRunner-Runner.app for tvOS
        run: |
          pushd $PKG_PATH_TVOS/Build/Products/Debug-appletvos
          zip -r $ZIP_PKG_NAME_TVOS WebDriverAgentRunner_tvOS-Runner.app
          popd
          mv $PKG_PATH_TVOS/Build/Products/Debug-appletvos/$ZIP_PKG_NAME_TVOS ./

      - name: Build iOS for simulator for arm64
        run: |
          xcodebuild clean build-for-testing \
            -project WebDriverAgent.xcodeproj \
            -derivedDataPath $PKG_PATH_IOS_SIM_ARM64 \
            -scheme WebDriverAgentRunner \
            -destination "platform=iOS Simulator,name=iPhone 14 Pro,OS=16.2" \
            CODE_SIGNING_ALLOWED=NO ARCHS=arm64
      - name: Creating a zip of WebDriverAgentRunner-Build-Sim for iOS
        run: |
          pushd $PKG_PATH_IOS_SIM_ARM64
          zip -r $ZIP_PKG_NAME_IOS_SIM_ARM64 Build
          popd
          mv $PKG_PATH_IOS_SIM_ARM64/$ZIP_PKG_NAME_IOS_SIM_ARM64 ./

      - name: Build iOS for simulator for x86_64
        run: |
          xcodebuild clean build-for-testing \
            -project WebDriverAgent.xcodeproj \
            -derivedDataPath $PKG_PATH_IOS_SIM_X86_64 \
            -scheme WebDriverAgentRunner \
            -destination "platform=iOS Simulator,name=iPhone 14 Pro,OS=16.2" \
            CODE_SIGNING_ALLOWED=NO ARCHS=x86_64
      - name: Creating a zip of WebDriverAgentRunner-Build-Sim for iOS
        run: |
          pushd $PKG_PATH_IOS_SIM_X86_64
          zip -r $ZIP_PKG_NAME_IOS_SIM_X86_64 Build
          popd
          mv $PKG_PATH_IOS_SIM_X86_64/$ZIP_PKG_NAME_IOS_SIM_X86_64 ./

      # - name: Build tvOS for simulator
      #   run: |
      #     xcodebuild clean build-for-testing \
      #       -project WebDriverAgent.xcodeproj \
      #       -derivedDataPath $PKG_PATH_TVOS_SIM \
      #       -scheme WebDriverAgentRunner_tvOS \
      #       -scheme WebDriverAgentRunner \
      #       -destination "platform=tvOS Simulator,name=Apple TV 4K,OS=16.0" \
      #       CODE_SIGNING_ALLOWED=NO ARCHS=arm64 x86_64
      # - name: Creating a zip of WebDriverAgentRunner-Build-Sim for iOS
      #   run: |
      #     pushd $PKG_PATH_TVOS_SIM
      #     zip -r $ZIP_PKG_NAME_TVOS_SIM Build
      #     popd
      #     mv $PKG_PATH_TVOS_SIM/$ZIP_PKG_NAME_TVOS_SIM ./

      - name: Upload the built generic app package for iOS
        uses: actions/upload-artifact@v3.1.0
        with:
          path: "${{ env.ZIP_PKG_NAME_IOS }}"
      - name: Upload the built generic app package for tvOS
        uses: actions/upload-artifact@v3.1.0
        with:
          path: "${{ env.ZIP_PKG_NAME_TVOS }}"
      - name: Upload the built generic app package for iOS Simulator for arm64
        uses: actions/upload-artifact@v3.1.0
        with:
          path: "${{ env.ZIP_PKG_NAME_IOS_SIM_ARM64 }}"
      - name: Upload the built generic app package for iOS Simulator for x86_64
        uses: actions/upload-artifact@v3.1.0
        with:
          path: "${{ env.ZIP_PKG_NAME_IOS_SIM_X86_64 }}"
      # - name: Upload the built generic app package for tvOS Simulator
      #   uses: actions/upload-artifact@v3.1.0
      #   with:
      #     path: "${{ env.ZIP_PKG_NAME_TVOS_SIM }}"
