name: Building WebDriverAgent

on:
  workflow_dispatch:

env:
  HOST: macos-12
  XCODE_VERSION: 14.2
  DESTI_IOS_SIM: platform=iOS Simulator,name=iPhone 14 Pro
  DESTI_TVOS_SIM: platform=tvOS Simulator,name=Apple TV

jobs:
  host_machine:
    runs-on: ubuntu-latest
    outputs:
      host: ${{ steps.macos_host.outputs.host }}
    steps:
      - run: |
          echo "host=${{ env.HOST }}" >> $GITHUB_OUTPUT
        id: macos_host

  for_real_devices:
    needs: [host_machine]
    name: Build WDA for real iOS and tvOS devices
    runs-on: ${{ needs.host_machine.outputs.host }}

    env:
      ZIP_PKG_NAME_IOS: "WebDriverAgentRunner-Runner.zip"
      ZIP_PKG_NAME_TVOS: "WebDriverAgentRunner_tvOS-Runner.zip"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "${{ env.XCODE_VERSION }}"
      - name: Build iOS
        run: sh $GITHUB_WORKSPACE/Scripts/build-ci.sh
        env:
          DERIVED_DATA_PATH: appium_wda_ios
          SCHEME: WebDriverAgentRunner
          DESTINATION: generic/platform=iOS
          ARCHS: arm64
      - name: Creating a zip of WebDriverAgentRunner-Runner.app for iOS
        run: |
          pushd appium_wda_ios/Build/Products/Debug-iphoneos
          zip -r $ZIP_PKG_NAME_IOS WebDriverAgentRunner-Runner.app
          popd
          mv appium_wda_ios/Build/Products/Debug-iphoneos/$ZIP_PKG_NAME_IOS ./

      - name: Build tvOS
        run: sh $GITHUB_WORKSPACE/Scripts/build-ci.sh
        env:
          DERIVED_DATA_PATH: appium_wda_tvos
          SCHEME: WebDriverAgentRunner_tvOS
          DESTINATION: generic/platform=tvOS
          ARCHS: arm64
          ZIP_PKG_NAME: "WebDriverAgentRunner-Runner.zip"
      - name: Creating a zip of WebDriverAgentRunner-Runner.app for tvOS
        run: |
          pushd appium_wda_tvos/Build/Products/Debug-appletvos
          zip -r $ZIP_PKG_NAME_TVOS WebDriverAgentRunner_tvOS-Runner.app
          popd
          mv appium_wda_tvos/Build/Products/Debug-appletvos/$ZIP_PKG_NAME_TVOS ./

      - name: Upload the built generic app package for iOS
        uses: actions/upload-artifact@v3.1.0
        with:
          path: "${{ env.ZIP_PKG_NAME_IOS }}"
      - name: Upload the built generic app package for tvOS
        uses: actions/upload-artifact@v3.1.0
        with:
          path: "${{ env.ZIP_PKG_NAME_TVOS }}"


  for_simulator_devices_x86_64:
    needs: [host_machine]
    name: Build WDA for simulator iOS and tvOS devices - x86-64
    runs-on: ${{ needs.host_machine.outputs.host }}

    env:
      ZIP_PKG_NAME_IOS_SIM_X86_64: "WebDriverAgentRunner-Build-Sim-x86-64.zip"

      ZIP_PKG_NAME_TVOS_SIM_X86_64: "WebDriverAgentRunner_tvOS-Build-Sim-x86-64.zip"
      PKG_PATH_TVOS_SIM_X86_64: ""

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "${{ env.XCODE_VERSION }}"
      - name: Build iOS for simulator for x86_64
        run: sh $GITHUB_WORKSPACE/Scripts/build-ci.sh
        env:
          DERIVED_DATA_PATH: appium_wda_ios_sim_x86_64
          SCHEME: WebDriverAgentRunner
          DESTINATION: platform=iOS Simulator,name=iPhone 14 Pro
          ARCHS: x86_64
      - name: Creating a zip of WebDriverAgentRunner-Build-Sim for iOS
        run: |
          pushd appium_wda_ios_sim_x86_64
          rm -rf Build/Intermediates.noindex
          zip -r $ZIP_PKG_NAME_IOS_SIM_X86_64 Build
          popd
          mv appium_wda_ios_sim_x86_64/$ZIP_PKG_NAME_IOS_SIM_X86_64 ./

      - name: Build tvOS for simulator for x86_64
        run: sh $GITHUB_WORKSPACE/Scripts/build-ci.sh
        env:
          DERIVED_DATA_PATH: appium_wda_tvos_sim_x86_64
          SCHEME: WebDriverAgentRunner_tvOS
          DESTINATION: platform=tvOS Simulator,name=Apple TV
          ARCHS: x86_64
      - name: Creating a zip of WebDriverAgentRunner-Build-Sim for iOS
        run: |
          pushd appium_wda_tvos_sim_x86_64
          rm -rf Build/Intermediates.noindex
          zip -r $ZIP_PKG_NAME_TVOS_SIM_X86_64 Build
          popd
          mv appium_wda_tvos_sim_x86_64/$ZIP_PKG_NAME_TVOS_SIM_X86_64 ./

      - name: Upload the built generic app package for iOS Simulator for x86_64
        uses: actions/upload-artifact@v3.1.0
        with:
          path: "${{ env.ZIP_PKG_NAME_IOS_SIM_X86_64 }}"
      - name: Upload the built generic app package for tvOS Simulator for x86_64
        uses: actions/upload-artifact@v3.1.0
        with:
          path: "${{ env.ZIP_PKG_NAME_TVOS_SIM_X86_64 }}"


  for_simulator_devices_arm64:
    needs: [host_machine]
    name: Build WDA for simulator iOS and tvOS devices - arm64
    runs-on: ${{ needs.host_machine.outputs.host }}

    env:
      ZIP_PKG_NAME_IOS_SIM_ARM64: "WebDriverAgentRunner-Build-Sim-arm64.zip"

      ZIP_PKG_NAME_TVOS_SIM_ARM64: "WebDriverAgentRunner_tvOS-Build-Sim-arm64.zip"
      PKG_PATH_TVOS_SIM_ARM64: "appium_wda_tvos_sim_arm64"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "${{ env.XCODE_VERSION }}"

      - name: Build iOS for simulator for arm64
        run: sh $GITHUB_WORKSPACE/Scripts/build-ci.sh
        env:
          DERIVED_DATA_PATH: appium_wda_ios_sim_arm64
          SCHEME: WebDriverAgentRunner
          DESTINATION: platform=iOS Simulator,name=iPhone 14 Pro
          ARCHS: arm64
      - name: Creating a zip of WebDriverAgentRunner-Build-Sim for iOS
        run: |
          pushd appium_wda_ios_sim_arm64
          rm -rf Build/Intermediates.noindex
          zip -r $ZIP_PKG_NAME_IOS_SIM_ARM64 Build
          popd
          mv appium_wda_ios_sim_arm64/$ZIP_PKG_NAME_IOS_SIM_ARM64 ./

      - name: Build tvOS for simulator for arm64
        run: sh $GITHUB_WORKSPACE/Scripts/build-ci.sh
        env:
          DERIVED_DATA_PATH: appium_wda_tvos_sim_arm64
          SCHEME: WebDriverAgentRunner_tvOS
          DESTINATION: platform=tvOS Simulator,name=Apple TV
          ARCHS: arm64
      - name: Creating a zip of WebDriverAgentRunner-Build-Sim for iOS
        run: |
          pushd appium_wda_tvos_sim_arm64
          rm -rf Build/Intermediates.noindex
          zip -r $ZIP_PKG_NAME_TVOS_SIM_ARM64 Build
          popd
          mv appium_wda_tvos_sim_arm64/$ZIP_PKG_NAME_TVOS_SIM_ARM64 ./

      - name: Upload the built generic app package for iOS Simulator for arm64
        uses: actions/upload-artifact@v3.1.0
        with:
          path: "${{ env.ZIP_PKG_NAME_IOS_SIM_ARM64 }}"
      - name: Upload the built generic app package for tvOS Simulator for arm64
        uses: actions/upload-artifact@v3.1.0
        with:
          path: "${{ env.ZIP_PKG_NAME_TVOS_SIM_ARM64 }}"
